name: huungry
description: "Hungry APP"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  image_picker: ^1.2.0
  animate_icons: ^2.0.0
  lottie: ^3.3.1
  model_viewer_plus: ^1.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/detail/
    - assets/icon/
    - assets/banner/
    - assets/lottie/
    - assets/3dModel/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

